version: "3.1"

services:
  valuator_app:
    scale: 3
    env_file: apps/.env
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: apps
      dockerfile: Valuator/Dockerfile
    depends_on:
      - redis_main
      - nats
      - rank_calculator_app
    networks:
      - valuator_network

  rank_calculator_app:
    scale: 2
    env_file: apps/.env
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: apps
      dockerfile: RankCalculator/Dockerfile
    stdin_open: true
    tty: true
    depends_on:
      - redis_main
    networks:
      - valuator_network 
  
  events_logger_app:
    scale: 2
    env_file: apps/.env
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: apps
      dockerfile: EventsLogger/Dockerfile
    stdin_open: true
    tty: true
    depends_on:
      - redis_main
    networks:
      - valuator_network  

  nginx:
    image: nginx:latest
    container_name: valuator_nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx/
    depends_on:
      - valuator_app
    networks:
      - valuator_network

  redis_main: &redis_main
    image: redis:latest
    container_name: valuator_redis_main
    ports:
      - "6379:6379"
    hostname: redis_main
    networks:
      - valuator_network

  redis_ru:
    <<: *redis_main
    container_name: valuator_redis_ru
    ports:
      - "6378:6379"
    hostname: redis_ru
  
  redis_eu:
    <<: *redis_main
    container_name: valuator_redis_eu
    ports:
      - "6377:6379"
    hostname: redis_eu

  redis_other:
    <<: *redis_main
    container_name: valuator_redis_other
    ports:
      - "6376:6379"   
    hostname: redis_other

  nats:
    image: nats
    container_name: valuator_nats
    networks: 
      - valuator_network

networks:
  valuator_network:
    